### ISSUE TITLE
Please make sure to provide a user-agent that identifies this software

### ISSUE THREAD

**Issue by jchesterpivotal** [cfmobile/gopivnet#2]
When we in the pivnet team are spelunking our logs, all the generic programming user agents (eg "Go-http-11") look similar and are difficult to filter.

We'd be very grateful if your tool gave us a user-agent, such as `gopivnet/<version or release number>`.

If you could also include some information about your calling environment in the user-agent that would be awesome too. For example, the pivnet-resource will give us user-agent strings of the form `pivnet-resource/0.4.0 https://example.com/a/path/to/a/concourse/build/123", which allows us to identify the team whose copy is making that request.

**Comment by ebabani** [comment]
Good point. I'll add a user agent string to the requests we do.

**Comment by ebabani** [comment]
Added in 16200b79bf4f1fce3118b845bb36fbd8f37d40cb
